### ISSUE TITLE
Back to previous on mobile

### ISSUE THREAD

**Issue by juuso-vaadin** [vaadin-component-factory/vcf-breadcrumb#6]
The component should have a mode where only parent link is shown.
This would be useful for the mobile version of the breadcrumbs where space is limited.
![Image](https://github.com/user-attachments/assets/2d95d363-8391-426c-85dd-933e5d4b98f1)

I managed to achieve this with CSS, but ideally this theme variant would be included in the component and the responsive breakpoint would be customizable.

````css
@media screen and (max-width: 600px) {

    vcf-breadcrumbs[theme~="mobile-back"] vcf-breadcrumb {
        display: none;
    }
    vcf-breadcrumbs[theme~="mobile-back"] vcf-breadcrumb:last-child:not([aria-current]),
    vcf-breadcrumbs[theme~="mobile-back"] vcf-breadcrumb:has(+ vcf-breadcrumb[aria-current]) {
        display: block;
    }

    vcf-breadcrumbs[theme~="mobile-back"] vcf-breadcrumb::part(separator) {
        display: none;
    }

    vcf-breadcrumbs[theme~="mobile-back"] vcf-breadcrumb a::before {
        display: inline-block;
        font-family: var(--vcf-breadcrumb-separator-font-family);
        content: var(--lumo-icons-angle-left);
        font-size: var(--vcf-breadcrumb-separator-size);
    }
}
````

**Comment by juuso-vaadin** [comment]
Here's the same based on container size
```css
/* Responsiveness based on container width */
vcf-breadcrumbs[theme~="mobile-back-container"] {
    container-type: inline-size;
}

@container (max-width: 480px) {
    vcf-breadcrumbs[theme~="mobile-back-container"] vcf-breadcrumb {
        display: none;
    }

    vcf-breadcrumbs[theme~="mobile-back-container"] vcf-breadcrumb:last-child:not([aria-current]),
    vcf-breadcrumbs[theme~="mobile-back-container"] vcf-breadcrumb:has(+ vcf-breadcrumb[aria-current]) {
        display: block;
    }

    vcf-breadcrumbs[theme~="mobile-back-container"] vcf-breadcrumb::part(separator) {
        display: none;
    }

    vcf-breadcrumbs[theme~="mobile-back-container"] vcf-breadcrumb a::before {
        display: inline-block;
        font-family: 'lumo-icons';
        content: var(--lumo-icons-angle-left);
        font-size: var(--vcf-breadcrumb-separator-size);
    }
}
```
